apiVersion: v1                         # Kubernetes API version for Service
kind: Service                          # Resource type: Service
metadata:                              # Metadata section for the Service
  name: my-python-cicd-app-service     # Service name
  namespace: cicd-app                  # Namespace where Service will be created

spec:                                  # Desired state of the Service
  type: ClusterIP                      # Internal Kubernetes service type
  selector:                            # Selects Pods by label
    app: my-python-cicd-app            # Must match Pod label in Deployment

  ports:                               # Service port mapping
    - protocol: TCP                    # Network protocol
      port: 80                         # Service port inside Kubernetes cluster
      targetPort: 5000                 # Container port where Flask app listens
